### ISSUE TITLE
it wont open

### ISSUE THREAD

**Issue by Raatty** [flathub/com.jagex.RuneScape#110]
error message when ran from command line 
```
/app/extra/runescape-launcher: line 18: /app/extra/runescape: No such file or directory
```

**Comment by MrCarroll** [comment]
The game update of 02/03/2020 updated the apt repository with a defective package. This package is a valid Debian package, but lacks the executable code for the launcher. As a result, Jagex is effectively not publishing a Linux package as of right now.

I've managed to inform Jagex of this issue, and presume they're working on a fix. The fix will likely come in the form of NXT Launcher 2.2.7 - which will be exactly the same executable as 2.2.6, but requires a newer version number to fix people who install via Apt and have the defective package.

Until then, I'd hold off updating this Flatpak until 2.2.7 - as upgrading to it will cause the problem above. No new installations will work either, whether with this package, or other formats, E.G, Snap, AUR, native.

https://secure.runescape.com/m=forum/forums?278,279,573,66145484

**Comment by Raatty** [comment]
good to hear that you know what the issue is at least, had to resort to booting windows today smh

**Comment by annadane** [comment]
They're taking forever to fix this. :/

**Comment by Raatty** [comment]
maybe they will release new client with the monday update, ~~or we could just flatpak the windows version~~On Mar 9, 2020 16:40, annadane <notifications@github.com> wrote:They're taking forever to fix this. :/

**Comment by MrCarroll** [comment]
The ideal thing Jagex could do is allow redistribution of the launcher so that third party packages could directly bundle its contents rather than try manipulate it at run/install time. I've forwarded that concern on to them, but I doubt any lawyer will see it as a priority and they tend to have conservative thoughts on keeping things under control, unlike say Valve, where you can absolutely package their launcher.

I've at one point tried Wine-ifying the game, although using Snapcraft - it wasn't an amazing solution. There's potential to it to the approach fixing issues such as the buffer underruns in the audio, but at the same time it creates a lot of new issues that ruin the whole experience IMO. 

With today being a Monday, there will be a game patch. With their being a game patch, the launcher may be rebuilt, and if it is, flathubbot will automatically find it and begin pushing it to users, so hopefully this issue will be fixed within the next 5-12 hours.

**Comment by annadane** [comment]
https://www.reddit.com/r/runescape/comments/fjke09/runescape_news_a_message_to_our_community/fknrhsz/

**Comment by Raatty** [comment]
day 14no no fix smh, i just do my spins on mobile now...

**Comment by Shin-Aska** [comment]
@Raatty If you are using a debian based distro, you can download and install an old version of the client for the mean time. I have a backup whose hash is from the december build. I could PM you a copy if you want.

**Comment by Garbee** [comment]
Just merged the latest update that landed about 2 hours ago to the debian package. So once that is live on the site (probably 10-20 minutes depending on time for the production stuff to update) re-test and see if the issue is resolved.

**Comment by MrCarroll** [comment]
The latest package is still defective.

I am confident it cannot be fixed (fully) without being marked as 2.2.7. This situation is really unfortunate however, if you take the deb package being rebuilt as Jagex did an NXT update and keep in mind their usual cadence, we might not expect another update for 2 more weeks if they don't fast track a fix.

For the Snap package, I've gone ahead and just started putting the launcher in the container itself. The current concern is the EULA prohibits doing this, but as far as I am concerned the EULA actually makes the exact situation these containers solve allowable, and you can see my justifications for it here.
https://github.com/MrCarroll/runescape-launcher/commit/678bbcda79207c1b020ebcf9419e225f6621b29c

I'm unsure if you'll want to take on that same level of risk. But as far as I'm concerned, the EULA actually does give permission. In the event Jagex does disagree, I'll have a fun time negotiating us Linux users a new license, and with the thousands of Linux users adding up to hundreds of thousands of dollars a year, I'd expect them to be willing to agree with me.

**Comment by barthalion** [comment]
Yes, I'd agree that `(...) you undertake not to, in whole or in part, copy, reproduce, disassemble, decompile, reverse-engineer or create derivative works of the Software; except where such copying is incidental to normal use of the Software; ` may be interpreted that repackaging of their bundle is actually permitted. It would be interesting to simply ask them.

**Comment by Garbee** [comment]
I think the key phrase is "incidental" in that last important phrase. Legal (though INAL) hat on, I'd interpret a lawyer's intent here as, "If it's copying when installed or by your system automatically, that's incidental and out of anyone's real control." I think it's pretty clear intent they don't want us copying the launcher and redistributing it.

This is not something I'd personally test. Should someone be able to get a written statement saying it's OK from Jagex, then I'd go for it. Or even better, have the license updated to reflect that by Jagex. Until it is directly clear, I'd rather not test any legal waters on this front. It's a clear and direct Jagex distribution problem. People need to keep getting on them to fix it. If that's by making the package work or clarifying license allowances, up to Jagex and the community to ask.

I can't condone putting Flathub at any level of clear legal risk because the community is frustrated. That's just not equitable.

**Comment by annadane** [comment]
Still seems to be unfixed after Monday update

**Comment by jtherrmann** [comment]
> @Raatty If you are using a debian based distro, you can download and install an old version of the client for the mean time. I have a backup whose hash is from the december build. I could PM you a copy if you want.

Would you be willing to PM me a copy of the working client?

**Comment by jtherrmann** [comment]
> @Raatty If you are using a debian based distro, you can download and install an old version of the client for the mean time. I have a backup whose hash is from the december build. I could PM you a copy if you want.

@Shin-Aska would you be willing to PM me a copy of the working client?

**Comment by Espionage724** [comment]
[According to this Reddit post](https://redd.it/fo657l) updated today (Mar 26th), "There will be a fix coming very soon"

**Comment by MrCarroll** [comment]
The 2.2.7 update has landed and works. When the Flatpak upgrades to it (Flathubbot should be doing its magic soon), the issue will hopefully be fixed!

**Comment by annadane** [comment]
Bah, getting a 404 not found. Hopefully by midnight it's fixed...

**Comment by MrCarroll** [comment]
Until the PR is manually approved, you can try running the build in the test repository.

`flatpak install --user https://dl.flathub.org/build-repo/16681/com.jagex.RuneScape.flatpakref`

**Comment by Raatty** [comment]
that build works ty, ill wait for the merge b4 ill call this fixed tho

**Comment by Shin-Aska** [comment]
Hi @jtherrmann ,
I am assuming you don't need it anymore because 2.2.7 is already out. You can download it directly here as well 

https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.7_amd64.deb

**Comment by annadane** [comment]
Still getting errors. Error: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.6_amd64.deb
error: Failed to install com.jagex.RuneScape: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.6_amd64.deb

**Comment by MrCarroll** [comment]
From what I'm gathering, the release is built but isn't being distributed, I wouldn't know why, but I think @Garbee may have to manually intervene here, as I'd have expected it to have automatically updated by now.

https://flathub.org/builds/#/apps/com.jagex.RuneScape is showing the build with the fix as unpublished.

**Comment by AWarbear** [comment]
All of runescape is currently down as far as I can see. Check OSRS twitter for updates

**Comment by Garbee** [comment]
Another PR just came in setting the version to 2.6. When it was 2.7 previously. Why can’t Jagex just be sane? 

I’ll look at this as soon as I’m home to see what exactly is being sent out then by Jagex and get it all right manually.

**Comment by annadane** [comment]
It seems to be 2.7 now, but the install times out

**Comment by bunatl** [comment]
Flathub is describing version 2.7 now. Also, my issue from #113 is gone (it had to be that checksum) however a new error occured - `Gtk-Message: 19:52:36.182: Failed to load module "atk-bridge"`

**Comment by Garbee** [comment]
>  however a new error occured - Gtk-Message: 19:52:36.182: Failed to load module "atk-bridge"

That is as old as the game itself on Linux. It's fine and the game should run fine (although ever seeing an error is bad.) But fixing this is all on Jagex's side.

**Comment by bunatl** [comment]
Well @Garbee the game launcher starts, however, it stops after 10% or 15% in loading and completely shut down.

No matter starting it from the terminal, software manager or menu... 
Any ideas?

**Comment by annadane** [comment]
As shitty as the game is with MTX and everything it would be entertainment to play the game during coronavirus quarantine, but no, they don't even include the launcher and don't fix it for 3+ weeks... what the hell are they doing at Jagex?

**Comment by Garbee** [comment]
It looks like the timeout is because the actual server that provides all this content is down. I'm getting failures establishing a connection in any browser on all OSes, using a terminal with custom CURL headers, and using their own install instructions on Ubuntu.

No updates will move forward here until Jagex gets this sorted and it's calmed down a bit. I don't want them rushing out-of-line patches around (like 2.7 back to 2.6 currently) and screwing more stuff up for us.

**Comment by jtherrmann** [comment]
> Hi @jtherrmann ,
> I am assuming you don't need it anymore because 2.2.7 is already out. You can download it directly here as well
> 
> https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.7_amd64.deb

@Shin-Aska Yep, I was able to install the Ubuntu/Debian package via the commands provided at https://www.runescape.com/download, thanks!

**Comment by bunatl** [comment]
> > Hi @jtherrmann ,
> > I am assuming you don't need it anymore because 2.2.7 is already out. You can download it directly here as well
> > https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.7_amd64.deb
> 
> @Shin-Aska Yep, I was able to install the Ubuntu/Debian package via the commands provided at https://www.runescape.com/download, thanks!

Interesting... I tried that as well and I got no errors during downloading or installation, the first loading bar got to 100% (improvement compared to flatpak) and it stops at around 10% on the second one. The loading window/client then closes itself and errors are printed out.

Therefore, the overall result is the same: not working.

**Comment by MrCarroll** [comment]
The overall Jagex infrastructure has been having difficulties for the past 7 hours, Website, Game Servers, backend databases, the whole lot.

I don't think there's an error with the Flatpak now that the correct version is built and marked for distribution. The errors with loading (bar the GTK errors) are all either offshoots of the absolute mayhem thats been going on in Jagex internally today, or potentially a seperate issue that's been ongoing for about a week, primary seems to effect central America, and is being looked at on an ongoing basis as is https://www.reddit.com/r/runescape/comments/fo657l/feedback_login_and_performance_issues/.

Either way, I'd assume they know about it, and everything is good as far as the Flatpak side is concerned IMO.

**Comment by Garbee** [comment]
> Also can you ping/urge them to look into it.

I have no special connections there. This package is 100% externally maintained since we believe it is a better mechanism for Linux users to consume applications with. All I can do is add another voice to the existing chorus of "It's broken".

All we can really do (since this is clearly a deep problem and I don't think they're foolish enough to not have alert infrastructure) is wait until they clean up their system and then make sure we are right once the wake is over.

**Comment by annadane** [comment]
All's ok here.

**Comment by Raatty** [comment]
still those damn audio glitches but i guess it launches now time to close after 24 days... I might of cancelled my member ship if I didn't already have the whole year paid for lolz

**Comment by Garbee** [comment]
Confirmed this morning it is now installing and the launcher is present in the current flatpak build.
