### ISSUE TITLE
icon on flathub missing until Content Blocking is off in Firefox

### ISSUE THREAD

**Issue by bam80** [flathub/com.jagex.RuneScape#57]
https://github.com/flathub/com.spotify.Client/issues/70

**Comment by Garbee** [comment]
As @TingPing said in the very issue you reference, Flathub doesn't want to re-host assets. If you have a method of solving the issue without hosting the assets directly, please let us know. Preferably in the [frontend](https://github.com/flathub/linux-store-frontend) repo. Otherwise, nothing is going to change here unless it comes from the infrastructure people.
