### ISSUE TITLE
Graphical Issues when Resuming from Suspend

### ISSUE THREAD

**Issue by chris-samberg** [flathub/com.jagex.RuneScape#60]
Whenever I resume from suspend with Runescape and log back in, my client doesn't render the graphics in the same way as before. It forces me to close the client and re-open a new one. I've attached an image of the graphical issue along with my debug log. It'd be great if there is a fix for this annoyance.

The issue doesn't seem like a Flatpak issue as I had the issue with an earlier, non-Flatpak version of the client.

![screenshot from 2019-02-16 00-10-13](https://user-images.githubusercontent.com/22353553/52894894-62d14400-317f-11e9-96f8-bd4a52596287.png)

**Comment by TingPing** [comment]
> The issue doesn't seem like a Flatpak issue as I had the issue with an earlier, non-Flatpak version of the client.

Then this is not the place to report it.

**Comment by chris-samberg** [comment]
Where would I report this then?

**Comment by Garbee** [comment]
With RuneScape. However, it is highly likely it is even beyond there control and at the GPU layer. So in that case, it would also be reported to your GPU provider. Which since running on LInux, they won't care to do anything.

Basically, it's a GPU or game client issue and no one will care to fix it. Beyond that, there is nothing that can be done in the flatpak to address it.
