### ISSUE TITLE
Wrong deb file size

### ISSUE THREAD

**Issue by fusion809** [flathub/com.jagex.RuneScape#66]
Hi,

I'm getting this update error:

```bash
Error: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.4_amd64.deb
```

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
This is on NixOS 19.03-pre, I'm not filing a PR as I can't see what's wrong with your packaging files. wget reports the file size as the same as what's in the com.jagex.RuneScape.json, and sha256 reports the sha256 reported therein too.

**Comment by Garbee** [comment]
PR #65 being merged in this morning should have fixed this. So try again and see if it works now. The server should have been updated hours ago. If it persists then let me know so I can look into the build pipeline and see if it is stuck.

**Comment by fusion809** [comment]
'tis all fixed now, thanks.

**Comment by Garbee** [comment]
Yea, so... I have the PR creation auto-mated (hourly check) when the deb is updated. But what I don't have is a way to auto-rebase and merge it. The API is there, but it didn't work quite right when I initially tested so I backed off and left it.

The problem with using the API to make the PR as myself, it works but I get no notification. So I have to specifically log in to GH and check the repo. Which I forget to do regularly since I am on Mac OS now. I guess I should setup an email push to alert myself...

**Comment by etam** [comment]
This is happening again.
The size now is 3017760 and sha256 sum is fde9f88de137e357ff297523704930de56a98e53e3152329f81346ae8cc6eeeb.

**Comment by Garbee** [comment]
Yea, that's what we have. The problem is some strict screenshot requirements that got turned on... I'll look into it in a little bit.
