### ISSUE TITLE
Wrong size for extra data

### ISSUE THREAD

**Issue by Nodeswitch** [flathub/com.jagex.RuneScape#8]
Hi,

I'm trying to install the Runescape flatpak, but I'm receiving the below error.

```
flatpak install flathub com.jagex.RuneScape
Installing: com.jagex.RuneScape/x86_64/stable from flathub
[####################] Downloading: 3.8 MB/3.8 MB (750.7 kB/s)  
error: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.4_amd64.deb
```

**Comment by Limero** [comment]
Once the build server has created the new build, you should be able to install it without any problems.

**Comment by coreybruce** [comment]
Still a issue

**Comment by 1legality** [comment]
This didn't last long.

I'm brand new to FlatPak so I'm not sure how to do it but here's the new sha256 and the new size.

sha256 : 9876fc313712eb421aca19c1b714fb0e39ed5c054f499e6758df7770344c3f19
size : 3018752

Is there a way to update it without passing by flathub?

**Comment by Limero** [comment]
@1legality Size is incorrect, you can use "du -b" to get the right one. If you want to help update it in the future, fork this repo, update the values (you can use Github's built-in editor) and create a pull request.

**Comment by PorcelainMouse** [comment]
So, I'm confused.  I'm getting this now.  Seems like that is wrong, but I don't know what to do.  Anyone else seeing this?

**Comment by Limero** [comment]
https://github.com/flathub/com.jagex.RuneScape/commit/b41e836a890c4eebf90e62db01d49a4a7b31896b should've fixed it, wait for the build server to build it.

**Comment by coreybruce** [comment]
I believe this bug has been fixed, I successfully installed the flatpack not long ago but if you guys want I can check again.

**Comment by Garbee** [comment]
Because the update was merged to add the new hash and build size. What happens is when the flatpak is installed on clients, the client pulls the RuneScape installer down. Since the maintainers here don't have permission to redistribute the Debian contents as a whole. To verify that download is correct, the size of the Debian in bytes and the sha256 hash of the file are both compared. If either fails, then the install of the flatpak doesn't continue. This means when Jagex updates their installer, the flatpak then has to be updated. 

Without Jagex having some kind of check system for new builds going out, this can't really be automated in an efficient way. So it's a manual process to update this information when they change something.

**Comment by matiasblomqvist** [comment]
Got the same error today on Kubuntu 18.04, everything is up to date.
Even the launcher version in the error message is the same 2.2.4

**Comment by brunoDoddle** [comment]
Same error too, to bad.

**Comment by Garbee** [comment]
I know, I'm working on the auto-updating script with this round. That way in the future as the package is updated on the next hour we'd have an automatic PR made to update the info. So, it will be slightly slower this time getting it updated. However, once this is done it should be a good bit faster in the future since we just need to merge a PR when it pops up.

**Comment by Garbee** [comment]
Finally got this done after messing around for a good portion of the day. PR #26 is open to add the auto-update functionality and #25 is an example of what it generates (minus the commit from 26 as well overlapping currently.) I'm getting these both merged together now. Then I'll setup a cron tomorrow on a remote server to do the hourly check. This should help us be updated very quickly after Jagex pushes an update, assuming they don't version bump.

**Comment by Garbee** [comment]
I merged the last update yesterday. If it still isn't out then the build process is backed up. Which is something we don't have control over. I'll take a look into it in a little bit and see if I can't get someone to poke it if it is stuck.

**Comment by Garbee** [comment]
Yup, [the build failed](https://flathub.org/builds/#/builders/2/builds/5212) for reasons I can't figure out from the output dump. I requested that someone with the right permissions ask for it to rebuild. It looks like a few things failed around the same time, so the build bot apparently had a hiccup.

**Comment by Garbee** [comment]
The restarted build passed. So the latest package should be available now and function correctly. Thank you for your patience.

**Comment by jjordantb** [comment]
Happening Again.

**Comment by Garbee** [comment]
I merged the latest change this morning. Try again now, if it still isn't functioning then the build bot is backed up again.

**Comment by cdegroot** [comment]
Just got the error message. https://github.com/flathub/com.jagex.RuneScape/pull/74 should fix it.

**Comment by jeffj1** [comment]
Hi I got the same error:
OpenSUSE Tumbleweed 20190512

```
        ID                           Arch            Branch          Remote          Download
 1. [✗] com.jagex.RuneScape          x86_64          stable          flathub         3.0 MB / 12.9 MB

Error: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.4_amd64.deb
error: Failed to install com.jagex.RuneScape: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.4_amd64.deb
```

**Comment by JackH3103** [comment]
I also have the same error on openSUSE Tumbleweed 20210524

```
        ID                           Branch          Op         Remote          Download
 1. [✗] com.jagex.RuneScape          stable          i          flathub         3.9 MB / 13.5 MB

Error: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.9_amd64.deb
error: Failed to install com.jagex.RuneScape: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.9_amd64.deb
```

**Comment by Garbee** [comment]
Yea, this will *always* happen as the binary gets updated before the flatpak. If you hit it in this time zone between updates, it fails.

PRs are made automatically for the changes ( like #164 for this one now.) The bot seems to not be auto-merging them, but that will get looked into shortly if I remember next week. They for now are manually merged once the test builds pass.

I'm going to lock this thread since this is just the state of distributing this via flatpak until we have PGP verification of the packages, see #23 .
