### ISSUE TITLE
Use Flatpak External Data Checker

### ISSUE THREAD

**Issue by Limero** [flathub/com.jagex.RuneScape#90]
I just read about the Flatpak External Data Checker, which can be used to check for updates for Flatpak applications. Is this something that could be useful for automatically updating RuneScape?

@Garbee you have some custom stuff running right now, right?

https://github.com/endlessm/flatpak-external-data-checker/
https://blogs.gnome.org/wjjt/2019/09/23/flatpak-external-data-checker/

**Comment by Garbee** [comment]
Yup, I had them turn it off for us. Unless something like this is done by Flathub, I'd rather keep the control. Because, well, the people who make the game itself. Plus I now *should* have auto-merging patches working. So it's all in one box and should be updated within an hour of an update going out.

Ideally the PGP Signature stuff will come one day and we won't need to worry at all about checksums anymore.

**Comment by Garbee** [comment]
With #105 merged we are now using the Flathub provided checker for updating this data.
