### ISSUE TITLE
Cursors not rendering 

### ISSUE THREAD

**Issue by ZeWolfTah** [flathub/com.jagex.RuneScape#91]
OS: Ubuntu 18.04.3 LTS
Issue description: After installing the client from here, it works just fine except the mouse cursors fail to render fully. The shape renders, but they appear as a very flat grey color.

This is a fresh Ubuntu install, so maybe I'm missing something I need. If anyone knows a solution to this issue I'd greatly appreciate it. For now my workaround is to uncheck the "custom cursors" box in the game's graphics settings, but I would like to have the Runescape cursors rendering again.

I'm fairly new to Linux, but I do have some experience using Unix for school so I can handle using the terminal if required, but my apologies if I'm missing something obvious.

**Comment by Garbee** [comment]
Nothing obviously wrong. Perhaps just a bad client or something from Jagex.

Due to the nature of the client too, there is no easy way to debug issues. All you can really do is hope the next update fixes things. Perhaps double-check with the client from Jagex installed directly too. If it isn't working with that, then you can file a report to Jagex to have them fix it. However, given the size of the Linux installs, that can be quite some time. If it works w/o flatpack but fails in Flatpak, then all that can really be done (in this context) is wait and keep trying with updates to see if it eventually just fixes itself.

There is no useful debug information given from the client as to what is going on. Jagex actively wants to prevent any kind of debugging of their client (for game security reasons.) So, not much that can be done. Sorry.

**Comment by DarkArc** [comment]
I suspect this is caused by/related to https://github.com/flatpak/flatpak/issues/2868

**Comment by DarkArc** [comment]
![image](https://user-images.githubusercontent.com/778012/107172643-da639380-6993-11eb-938a-c0cf36c78d28.png)
This has been fixed upstream by https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/4342 this can be closed :)
